# Generated by Django 3.2.1 on 2022-03-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0003_alter_food_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food',
            new_name='Popular',
        ),
        migrations.AlterModelOptions(
            name='popular',
            options={'verbose_name_plural': 'Popular'},
        ),
    ]
