# Generated by Django 3.2.1 on 2022-03-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0004_auto_20220302_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='popular',
            name='digital',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
