# Generated by Django 3.2.1 on 2022-03-02 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0006_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
